#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Styling, testing your project before committing...'

# Check tsconfig standards
yarn check-types ||
(
    echo 'Failed Type check...'
    false;
)

yarn lint ||
(
    echo 'ESLint Check Failed...'
    false; 
)

yarn prettier ||
(
    echo 'Prettier Check Failed...';
    false;
)

git add -A

npx lint-staged

echo 'Committing...'