#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Styling, testing your project before committing...'

npx lint-staged

# Check tsconfig standards
yarn check-types ||
(
    echo 'Failed Type check...'
    false;
)

echo 'Committing...'